-- Authentication Tables Migration
-- Creates tables for MSME, Lender/NBFC, and Regulator users

-- ============================================
-- 1. MSME Users Table
-- ============================================
CREATE TABLE IF NOT EXISTS msme_users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    gstin VARCHAR(15) UNIQUE NOT NULL,
    contact_person VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    address TEXT,
    city VARCHAR(100),
    state VARCHAR(100),
    pincode VARCHAR(10),
    is_active BOOLEAN DEFAULT true,
    is_verified BOOLEAN DEFAULT false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP
);

-- Index for faster lookups
CREATE INDEX IF NOT EXISTS idx_msme_email ON msme_users(email);
CREATE INDEX IF NOT EXISTS idx_msme_gstin ON msme_users(gstin);

-- ============================================
-- 2. Lender/NBFC Users Table
-- ============================================
CREATE TABLE IF NOT EXISTS lender_users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    lender_name VARCHAR(255) NOT NULL,
    lender_type VARCHAR(50) NOT NULL, -- 'BANK', 'NBFC', 'FINTECH'
    license_number VARCHAR(100) UNIQUE NOT NULL,
    contact_person VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    address TEXT,
    city VARCHAR(100),
    state VARCHAR(100),
    pincode VARCHAR(10),
    is_active BOOLEAN DEFAULT true,
    is_verified BOOLEAN DEFAULT false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP
);

-- Index for faster lookups
CREATE INDEX IF NOT EXISTS idx_lender_email ON lender_users(email);
CREATE INDEX IF NOT EXISTS idx_lender_license ON lender_users(license_number);

-- ============================================
-- 3. Regulator Users Table (Admin)
-- ============================================
CREATE TABLE IF NOT EXISTS regulator_users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    role VARCHAR(50) DEFAULT 'ADMIN',
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP
);

-- Index for faster lookups
CREATE INDEX IF NOT EXISTS idx_regulator_email ON regulator_users(email);

-- ============================================
-- 4. Insert Default Admin User
-- Password: admin@123 (hashed with bcrypt)
-- ============================================
-- Note: The actual hash will be generated by the application
-- This is a placeholder that will be replaced by the migration script
INSERT INTO regulator_users (email, password_hash, full_name, role, is_active)
VALUES (
    'admin@gmail.com',
    '$2b$10$placeholder_will_be_replaced_by_script',
    'System Administrator',
    'ADMIN',
    true
)
ON CONFLICT (email) DO NOTHING;

-- ============================================
-- 5. Refresh Tokens Table (for JWT)
-- ============================================
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    user_type VARCHAR(20) NOT NULL, -- 'MSME', 'LENDER', 'REGULATOR'
    token VARCHAR(500) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_revoked BOOLEAN DEFAULT false
);

-- Index for faster lookups
CREATE INDEX IF NOT EXISTS idx_refresh_token ON refresh_tokens(token);
CREATE INDEX IF NOT EXISTS idx_refresh_user ON refresh_tokens(user_id, user_type);

-- ============================================
-- 6. Audit Log Table (Track all auth activities)
-- ============================================
CREATE TABLE IF NOT EXISTS auth_audit_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID,
    user_type VARCHAR(20), -- 'MSME', 'LENDER', 'REGULATOR'
    email VARCHAR(255),
    action VARCHAR(50) NOT NULL, -- 'REGISTER', 'LOGIN', 'LOGOUT', 'PASSWORD_CHANGE'
    ip_address VARCHAR(45),
    user_agent TEXT,
    status VARCHAR(20) NOT NULL, -- 'SUCCESS', 'FAILED'
    failure_reason TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index for audit queries
CREATE INDEX IF NOT EXISTS idx_audit_user ON auth_audit_log(user_id, user_type);
CREATE INDEX IF NOT EXISTS idx_audit_action ON auth_audit_log(action, created_at);

-- ============================================
-- 7. Update Timestamp Triggers
-- ============================================

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Triggers for MSME users
DROP TRIGGER IF EXISTS update_msme_users_updated_at ON msme_users;
CREATE TRIGGER update_msme_users_updated_at
    BEFORE UPDATE ON msme_users
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Triggers for Lender users
DROP TRIGGER IF EXISTS update_lender_users_updated_at ON lender_users;
CREATE TRIGGER update_lender_users_updated_at
    BEFORE UPDATE ON lender_users
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Triggers for Regulator users
DROP TRIGGER IF EXISTS update_regulator_users_updated_at ON regulator_users;
CREATE TRIGGER update_regulator_users_updated_at
    BEFORE UPDATE ON regulator_users
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- 8. Comments for Documentation
-- ============================================

COMMENT ON TABLE msme_users IS 'Stores MSME (Micro, Small, Medium Enterprises) user accounts';
COMMENT ON TABLE lender_users IS 'Stores Lender/NBFC user accounts';
COMMENT ON TABLE regulator_users IS 'Stores Regulator/Admin user accounts';
COMMENT ON TABLE refresh_tokens IS 'Stores JWT refresh tokens for session management';
COMMENT ON TABLE auth_audit_log IS 'Audit log for all authentication activities';

COMMENT ON COLUMN msme_users.gstin IS 'Goods and Services Tax Identification Number (unique)';
COMMENT ON COLUMN lender_users.lender_type IS 'Type of lender: BANK, NBFC, or FINTECH';
COMMENT ON COLUMN lender_users.license_number IS 'RBI license number or registration number';
